### ISSUE TITLE
🐛 Record Counts Issues

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2545]
## Describe the bug
Issue is found in staging as well. 

1. https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/HNAHAL-CA/clinical-data?donorId=&tab=primary_diagnosis
![Screen Shot 2023-01-17 at 12 31 10 PM](https://user-images.githubusercontent.com/8744047/212970465-f5f76d78-1675-4f9a-93e7-fae43bb9c3f9.png)

same issue found in https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/ALEXIS-CA/clinical-data?tab=primary_diagnosis

2. https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/HNAHAL-CA/clinical-data?donorId=&tab=radiation
![Screen Shot 2023-01-17 at 12 32 17 PM](https://user-images.githubusercontent.com/8744047/212970707-f003d889-87c4-43ab-b984-2e9ce655b1be.png)

**Comment by demariadaniel** [comment]
This is impacted by #2554 so we should mark that as a prerequisite first and revisit once that issue is in Develop

**Comment by daniel-cy-lu** [comment]
@Buwujiu This issue like Dan had sugguested is resolved from his other bug fixing ticket in Submitted Data Page. I've done testing in DEV and localhost for a couple of times in different programs, and the issue is not appearing.

**Comment by Buwujiu** [comment]
@daniel-cy-lu still seeing in issue such as, https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/HNAHAL-CA/clinical-data?donorId=&tab=radiation 
there are only 5 records, but page says 18.

**Comment by demariadaniel** [comment]
This is connected to clinical issue https://github.com/icgc-argo/argo-clinical/issues/922

Issue addressed by PRs https://github.com/icgc-argo/argo-clinical/pull/919 (Clinical) + https://github.com/icgc-argo/platform-ui/pull/2594 (UI)

**Comment by Buwujiu** [comment]
Tested in QA, working as expected!
