### ISSUE TITLE
🐛 Errors Persist After Fixing Data Issues

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2551]
## Describe the bug
on the submitted data page, errors might show up if a new version of dictionary is released. After correcting the errors, they should no longer be displayed on the submitted page. However, in staging, errors continues to show up after errors are fixed.

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to a program with existing data issues, 
2. fix the errors by re-submitting clinical data
3. go back to submitted page, errors still exist
example: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/ALEXIS-CA/clinical-data?donorId=&tab=treatment
![Screen Shot 2023-01-18 at 12 22 35 PM](https://user-images.githubusercontent.com/8744047/213251495-8834d5f9-3b3e-4c86-b2db-19c4c2136aa6.png)

Also reproducible in staging https://platform.staging.icgc-argo.org/submission/program/ALEXIS-INTL/clinical-data?donorId=&tab=treatment

## Expected behaviour
In this example, there should be no errors on `response_to_treatment_criteria_method` and `is_primary_treatment `

**Comment by demariadaniel** [comment]
Fixed by https://github.com/icgc-argo/argo-clinical/pull/884

which will be part of Clinical RC 1.75.0 https://github.com/icgc-argo/argo-clinical/pull/900

**Comment by Buwujiu** [comment]
Tested in ALEXIS-Ca, ALEXIS-INTL, working as expected.

**Comment by lindaxiang** [comment]
1. immunotherapy table has been updated for donor DO250571, however after updated, 
- the old and updated records are both showing in the table, 
- the error message still persist and does not match with what are showing in the table.
<img width="935" alt="Screenshot 2023-05-05 at 5 14 38 PM" src="https://user-images.githubusercontent.com/7522294/236570428-e8689496-208a-47ff-bd70-a3a4c173c25d.png">


2. followup table has been updated, however
- the error message still persist and does not match with what are showing in the table.
<img width="1134" alt="Screenshot 2023-05-05 at 5 23 07 PM" src="https://user-images.githubusercontent.com/7522294/236571094-43681e4f-3ed3-407e-893b-f727eeecbe6f.png">

**Comment by edsu7** [comment]
Bug Linda described is consistent. Tested in staging and QA.
![Screen Shot 2023-05-08 at 11 13 48 AM](https://user-images.githubusercontent.com/22638361/236862743-478a3f0d-1f25-400e-8d1a-4b92115b96d9.png)

![image](https://user-images.githubusercontent.com/22638361/236862818-7312b9f3-845d-4a21-a3e9-9b0539118fcb.png)

- same number of errors still reported despite updates to address migration errors
- correct field flagged as incorrect

**Comment by Buwujiu** [comment]
Logged issue in https://github.com/icgc-argo/platform-ui/issues/2654, will move this ticket forward.

**Comment by lindaxiang** [comment]
Tested in Prod for project TEST-INTL.
1. There's one error for Donor DO252288 (DN495) on primary diagnosis table
<img width="1293" alt="Screenshot 2023-05-11 at 5 28 33 PM" src="https://github.com/icgc-argo/platform-ui/assets/7522294/6513d012-575e-4c0e-a30e-600442d17a06">

2. I download the primary diagnosis data and fix the error for this Donor, then submit the updated table. The submission summary tells me I've successfully update the record for that donor
<img width="1510" alt="Screenshot 2023-05-11 at 5 32 40 PM" src="https://github.com/icgc-argo/platform-ui/assets/7522294/d1dd7014-a17f-4dee-b5d2-32beae7bba0c">

3. I check the status on primary diagnosis table, the error of Donor DO252288 (DN495)'s record disappear as expected
![Screenshot 2023-05-12 at 12 47 09 PM](https://github.com/icgc-argo/platform-ui/assets/7522294/03322de1-b529-44eb-b1d8-5e66074f43fe)
